export const tickets = [
  {
    id: 1,
    img:'/src/assets/yalin.jpeg',
    header: "Yalın Konseri",
    date: "20 Şubat 2026",
    price: "1500 TL",
  },
  { id: 2, 
     img:'/src/assets/yalin.jpeg',
    header: "Yalın Konseri",
    date: "20 Şubat 2026",
    price: "1500 TL", },
  {
     id: 3, 
    img:'/src/assets/yalin.jpeg',
    header: "Yalın Konseri",
    date: "20 Şubat 2026",
    price: "1500 TL",
  },
   {
    id: 4,
    img:'/src/assets/yalin.jpeg',
    header: "Yalın Konseri",
    date: "20 Şubat 2026",
    price: "1500 TL",
  },
  { id: 5, 
     img:'/src/assets/yalin.jpeg',
    header: "Yalın Konseri",
    date: "20 Şubat 2026",
    price: "1500 TL", },
  {
    id:6,
    img:'/src/assets/yalin.jpeg',
    header: "Yalın Konseri",
    date: "20 Şubat 2026",
    price: "1500 TL",
  },
  { id: 7, 
     img:'/src/assets/yalin.jpeg',
    header: "Yalın Konseri",
    date: "20 Şubat 2026",
    price: "1500 TL", },
  {
    id:8,
    img:'/src/assets/yalin.jpeg',
    header: "Yalın Konseri",
    date: "20 Şubat 2026",
    price: "1500 TL",
  },
];
